# Generated by Django 5.2 on 2025-04-09 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('pub_date', models.DateField()),
                ('category', models.CharField(choices=[('it', 'IT & Software'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('engineering', 'Engineering'), ('construction', 'Construction'), ('legal', 'Legal'), ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('government', 'Government'), ('arts', 'Arts & Media'), ('others', 'Others')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.job')),
            ],
        ),
    ]
